defaults: &defaults
  email_inbox: 'xxpressyaselfdev@gmail.com'
  port: '80'

development:
  <<: *defaults
  port: '3000'

test:
  <<: *defaults

production:
  <<: *defaults
  email_inbox: 'xxpressyaself@gmail.com'
